#!/bin/bash 
awk '$1 == "1" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "2" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "3" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "4" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "5" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "6" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "7" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "8" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "9" {total += $2; count++} END {print total/count }' average.txt >> 1tmp.txt
awk '$1 == "10" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "11" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "12" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "13" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "14" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "15" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "16" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "17" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "18" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "19" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "20" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "21" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "22" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "23" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "24" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "25" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "26" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "27" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt
awk '$1 == "28" {total += $2; count++} END {print total/count }' average.txt >> 1dtmp.txt

minimum="$(head -n 1 1dtmp.txt)"
awk -v m="$minimum" '{ print m/$1 }' 1dtmp.txt > 1doutputtmp.txt
rm 1dtmp.txt
cat -n 1doutputtmp.txt > 1doutput.txt
rm 1doutputtmp.txt
